# Generated by Django 2.2.7 on 2020-08-13 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_delete_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Blog',
        ),
    ]
