# Generated by Django 2.2.7 on 2020-08-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200813_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_comment',
            field=models.DateField(auto_now_add=True),
        ),
    ]
