# Generated by Django 2.2.7 on 2020-08-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200813_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
