# Generated by Django 2.2.7 on 2020-08-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='profile',
            field=models.ImageField(upload_to='media/country/'),
        ),
    ]
