# Generated by Django 2.2.7 on 2020-08-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200814_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='profile',
            field=models.ImageField(upload_to='country/'),
        ),
    ]
