# Generated by Django 2.2.7 on 2020-08-19 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_gamestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestatus',
            old_name='w0n',
            new_name='won',
        ),
    ]
