# Generated by Django 2.2.7 on 2020-08-19 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200819_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstVsSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_country', models.CharField(max_length=100)),
                ('first_country_flag', models.ImageField(upload_to='country/')),
                ('second_country', models.CharField(max_length=100)),
                ('second_country_flag', models.ImageField(upload_to='country/')),
                ('match_date', models.DateField()),
                ('local_time', models.DateTimeField()),
                ('stadium_city', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='gamestatu',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FirstVsSecond'),
        ),
    ]
