# Generated by Django 2.2.7 on 2020-08-19 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200819_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestatu',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
        ),
        migrations.DeleteModel(
            name='FirstVsSecond',
        ),
    ]
