# Generated by Django 2.2.7 on 2020-08-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200819_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameStatu',
        ),
    ]
