# Generated by Django 2.2.7 on 2020-08-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_gamestatu'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('country_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Country')),
            ],
        ),
        migrations.CreateModel(
            name='CountryPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Country')),
            ],
        ),
        migrations.CreateModel(
            name='CountryMatchStatu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_play', models.CharField(max_length=30)),
                ('won', models.CharField(max_length=30)),
                ('draw', models.CharField(max_length=30)),
                ('lost', models.CharField(max_length=30)),
                ('pts', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Country')),
            ],
        ),
        migrations.CreateModel(
            name='CountryBlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumbnail_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('country_post_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CountryBlog')),
            ],
        ),
    ]
