# Generated by Django 2.2.7 on 2020-08-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_countryblog_countryblogimage_countrymatchstatu_countryplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryblog',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
