# Generated by Django 2.2.7 on 2020-08-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_countryblog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryblog',
            name='feature_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='countryblog',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='CountryBlogImage',
        ),
    ]
