# Generated by Django 2.2.7 on 2020-08-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200819_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryplayers',
            name='number',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
