# Generated by Django 2.2.7 on 2020-08-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_countryplayers_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryplayers',
            name='number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
