# Generated by Django 2.2.7 on 2020-08-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200819_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('name', 'slug')},
        ),
    ]
