# Generated by Django 2.2.7 on 2020-08-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200820_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='feature_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
