# Generated by Django 2.2.7 on 2020-08-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_country_feature_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='feature_img',
        ),
    ]
